### PR TITLE
Syn 151 save zoom level with projects so they are restored when reopening

### PR DESCRIPTION
**Pull request by leny-mi**
## Describe your changes

- Zoom level is stored when switching between process models
- Refactored yjs document creation to fix bugs when switching between process models

## Checklist before requesting a review
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by MathiasBoi6** [comment]
'Phantom' process models are generated, and accessing them, generates an error (see images).
Opening a process model from home, does not use the stored zoom information, which is weird for some cases. Example have 2 process models in the navigation bar, and move your camera to a different position in both. If you go to home and then open one of them, the camera will be in the initial position, but if you open the other project in the navigation bar and then return the the first project through the navigation bar, your camera will be at the place that was saved when you had moved the camera. (Viewport may be more apt than camera here.)

image
image

**Comment by MathiasBoi6** [comment]
https://user-images.githubusercontent.com/79922317/236819585-e9022450-048c-4f79-aa90-6c5db91122b3.mp4

In case you cannot reproduce the problem, here is a video

**Comment by leny-mi** [comment]
Ohh, I saw them but somehow assumed they were caused by something else. I'll fix it, thanks!

**Comment by MathiasBoi6** [comment]
> Ohh, I saw them but somehow assumed they were caused by something else. I'll fix it, thanks!

The problem is also in one of your other PR's, so it seems to be a problem in main. I'll add it to jira.

I'll approve if you are satisfied with how the zoom is saved/reproduced

**Pull request merged**
